### PR TITLE
Yale blue -> Columbia blue

### PR DESCRIPTION
**Pull request by inchkev**

### CODE REVIEW

**Review by ErikBoesen — CHANGES_REQUESTED** [review]
Fucking sinner

**Comment by kchen1250** [comment]
oh now I've been found out (I call this outreach my real allegiance is still #00356B)

**Comment by inchkev** [comment]
ᶜʰᶦˡˡ ᶦᵐ ʲᵘˢᵗ ᵗʳʸᶦⁿᵍ ᵗᵒ ʰᵉˡᵖ ᵗʰᵉᵐ

**Comment by Radilx** [comment]
#730D00 is red, not blue.

**Comment by inchkev** [comment]
Oops, flipped rgb. Will commit with #000D74 soon

**Comment by Radilx** [comment]
np! just wanted to make sure it wasn't merged haha.

**Comment by ErikBoesen** [comment]
@kchen1250 Yeah of course, I'm just kidding

**Pull request merged**
